### ISSUE TITLE
Retailer Download

### ISSUE THREAD

**Issue by afolabi93** [ezechinwa/hotspot_tracking#1]
I tried downloading retailers' information but the data downloaded are scattered
[retailers (5).csv](https://github.com/ezechinwa/hotspot_tracking/files/9021400/retailers.5.csv)
.

**Comment by ezechinwa** [comment]
Hi Afolabi
Can I close this issue, and has this been resolved.

**Comment by afolabi93** [comment]
yes

**Comment by ezechinwa** [comment]
Resolved

**Comment by ezechinwa** [comment]
fixed
