### ISSUE TITLE
Customer Search

### ISSUE THREAD

**Issue by afolabi93** [ezechinwa/hotspot_tracking#2]
We cant search for customer details

![Screenshot (112)](https://user-images.githubusercontent.com/108480962/176726387-c0420734-8db1-4b71-a552-ace4364fd823.png)
![Screenshot (111)](https://user-images.githubusercontent.com/108480962/176726392-2df3dc83-7839-4be5-8488-baadba4114a3.png)
s

**Comment by ezechinwa** [comment]
This is currently getting worked on and would be resolved in about 2 hours
