### ISSUE TITLE
Internet Connection

### ISSUE THREAD

**Issue by afolabi93** [ezechinwa/hotspot_tracking#6]
Very slow loading of Hotspot landing page

**Comment by ezechinwa** [comment]
<img width="1439" alt="Screenshot 2022-07-03 at 4 51 14 AM" src="https://user-images.githubusercontent.com/17327631/177023830-6dd4bc4b-0ae2-42a5-a3b2-1bbe4726a3cb.png">


 I have optimized the page , now loads within 8s - 10 sec with a slow internet
