### ISSUE TITLE
Multiple Account Holder

### ISSUE THREAD

**Issue by afolabi93** [ezechinwa/hotspot_tracking#7]
Some customer and retailer account holders cant see both accounts when signed in.
Case study: 2348024278872 and 234703860735
![WhatsApp Image 2022-07-02 at 2 48 02 PM](https://user-images.githubusercontent.com/108480962/177011793-cb0be5eb-7a49-42d2-a22f-b5bdc2699b98.jpeg)

**Comment by ezechinwa** [comment]
![Screenshot 2022-07-03 at 2 13 46 AM](https://user-images.githubusercontent.com/17327631/177020644-8e4c7517-bb7f-4331-bc64-aa36d50b9d29.png)
fixed
