### ISSUE TITLE
Payment Details

### ISSUE THREAD

**Issue by afolabi93** [ezechinwa/hotspot_tracking#8]
Tizeti Zenith bank details should be added to the mode of payment
Also the grammar highlighted should be corrected, **_**_"Kindly your retailer name, number and proof of payment to hotspot@tizeti.com"_*_**
![Capture](https://user-images.githubusercontent.com/108480962/177061175-32ff13b1-b15a-4268-9f6e-945dc36b0acf.JPG)
*

**Comment by ezechinwa** [comment]
fixed
